name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Criar pasta dist
        run: mkdir -p dist

      - name: Gerar Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: luizferreira
          output: dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Gerar Snake Dark
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: luizferreira
          output: dist/github-contribution-grid-snake-dark.svg
          palette: github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push para branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
